#!/bin/bash
dpkg-deb -bZgzip projects/system/repoicons debs
dpkg-deb -bZgzip projects/others/ew1pagedots debs
dpkg-deb -bZgzip projects/LS/lsew198 debs
dpkg-deb -bZgzip projects/LS/lsew199 debs
dpkg-deb -bZgzip projects/LS/lsew92 debs
dpkg-deb -bZgzip projects/fonts/fontglober9 debs
dpkg-deb -bZgzip projects/fonts/fontglober1011 debs
dpkg-deb -bZgzip projects/fonts/fontglobertm debs
dpkg-deb -bZgzip projects/HS/ew88iwgt debs
dpkg-deb -bZgzip projects/HS/sbew88 debs
dpkg-deb -bZgzip projects/HS/sbew88xi debs
dpkg-deb -bZgzip projects/HS/sbew88fp debs
dpkg-deb -bZgzip projects/fonts/fontopensans1011 debs
dpkg-deb -bZgzip projects/fonts/fontbrandontext1011 debs
dpkg-deb -bZgzip projects/LS/lsewbatteryxi debs
dpkg-deb -bZgzip projects/LS/lsewlegacyxi debs
dpkg-deb -bZgzip projects/LS/lsew24xi debs
dpkg-deb -bZgzip projects/LS/lsew22xi debs
dpkg-deb -bZgzip projects/LS/lsew13xi debs
dpkg-deb -bZgzip projects/LS/lsew11xi debs
dpkg-deb -bZgzip projects/LS/lsew10xi debs
dpkg-deb -bZgzip projects/HS/sbew34ai debs
dpkg-deb -bZgzip projects/HS/sbew30ai debs
dpkg-deb -bZgzip projects/HS/sbew29ai debs
dpkg-deb -bZgzip projects/LS/lsew8xi debs
dpkg-deb -bZgzip projects/LS/lsew6xi debs
dpkg-deb -bZgzip projects/LS/lsew5xi debs
dpkg-deb -bZgzip projects/LS/lsew4xi debs
dpkg-deb -bZgzip projects/LS/lsew3xi debs
dpkg-deb -bZgzip projects/LS/lsew2xi debs
